[versions]
androidGradlePlugin = "8.5.0"
kotlin = "2.0.0"
coreKtx = "1.13.1"
junit = "4.13.2"
junitExtensions = "1.2.1"
espressoCore = "3.6.1"
appcompat = "1.7.0"
material = "1.12.0"
detekt = "1.23.6"
kotlinter = "4.4.0"
material3 = "1.2.1"

# Project configuration
namespace = "com.rjspies.phosphoricons"
minSdk = "24"
targetSdk = "34"
compileSdk = "34"
version = "1.0.0"
versionCodeOffset = "20000"
javaVersion = "21"
javaVendor = "Oracle"

[libraries]
androidxCore-coreKtx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
junit-junit = { group = "junit", name = "junit", version.ref = "junit" }
androidxTestExt-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitExtensions" }
androidxTestEspresso-espressoCore = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
androidxAppcompat-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
comGoogleAndroidMaterial-material = { group = "com.google.android.material", name = "material", version.ref = "material" }
androidxCompose-material3 = { group = "androidx.compose.material3", name = "material3", version.ref = "material3" }

[plugins]
comAndroidApplication = { id = "com.android.application", version.ref = "androidGradlePlugin" }
comAndroidLibrary = { id = "com.android.library", version.ref = "androidGradlePlugin" }
orgJetbrainsKotlinAndroid = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
ioGitlabArturboschDetekt = { id = "io.gitlab.arturbosch.detekt", version.ref = "detekt" }
orgJmailenKotlinter = { id = "org.jmailen.kotlinter", version.ref = "kotlinter" }
orgJetbrainsKotlinPluginCompose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
